

replicaCount: 2

namedeployment: web-deployment
nameservice: web-service


image:
  repository: bmtmapprao/java
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

container:
  port: 8080



service:
  type: ClusterIP
  port: 80

