apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namedeployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.namedeployment }}
  template:
    metadata:
      labels:
        app: {{ .Values.namedeployment }}
    spec:
      containers:
      - name: abc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.container.port }}